In [2]:
import numpy as np

In [4]:
data = np.array([2,4,6,8,10])

In [5]:
print(data)
print(type(data))
print(data.shape)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
(5,)


In [6]:
data = np.arange(15)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
data = np.random.rand(15)
print(data)

[0.14575144 0.11530594 0.48972632 0.54800687 0.21460113 0.57271236
 0.86310182 0.31211743 0.1213503  0.3963097  0.31075303 0.46584921
 0.53994759 0.96990171 0.63635091]


In [8]:
data = np.random.randint(10, size=10)
print(data)

[0 9 7 4 2 9 2 3 9 6]


In [18]:
data = np.random.random((2,2))
print(data)

[[0.50720805 0.40740001]
 [0.3790311  0.04291408]]


In [20]:
data = np.zeros((3,4))
print(data)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
data = np.ones((3,4))
print(data)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
data = np.empty((3,4))
print(data)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
data = np.arange(10) * -1
print(data)

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [24]:
tamanho = 10
data = np.random.permutation(tamanho)
print(data)

[6 9 0 7 3 2 8 5 4 1]


In [25]:
data = np.random.randint(5, size = 10)
print(data)
print(data.shape)

[2 1 0 4 2 2 4 1 0 4]
(10,)


In [26]:
data = np.random.randint(5, size = (3,4))
print(data)
print(data.shape)

[[2 1 0 1]
 [0 4 1 3]
 [1 3 2 1]]
(3, 4)


In [27]:
data = np.random.randint(5, size = (5,3,4))
print(data)
print(data.shape)

[[[1 0 4 3]
  [2 3 4 1]
  [1 0 3 4]]

 [[1 4 1 0]
  [4 4 4 2]
  [4 2 4 4]]

 [[2 2 4 3]
  [0 3 4 4]
  [3 2 1 2]]

 [[0 2 1 3]
  [2 2 3 3]
  [1 4 2 3]]

 [[1 1 2 0]
  [3 3 4 0]
  [2 0 2 1]]]
(5, 3, 4)


In [28]:
data = np.array([[1,2,3,4],[1,3,5,7]])
print(data)
print(data.shape)

[[1 2 3 4]
 [1 3 5 7]]
(2, 4)


In [29]:
data = np.array([(1,2,3,4),(1,3,5,7)])
print(data)
print(data.shape)
data_flat = data.flatten()
print(data_flat)
print(data_flat.shape)

[[1 2 3 4]
 [1 3 5 7]]
(2, 4)
[1 2 3 4 1 3 5 7]
(8,)


In [31]:
data = np.random.randint(5, size = (4,3,4))
print(data)
print(data.shape)
print(data.ndim)
print(data.size)

[[[2 1 4 1]
  [3 2 4 3]
  [0 3 0 0]]

 [[4 4 2 1]
  [3 2 1 3]
  [1 4 4 3]]

 [[0 0 0 3]
  [1 2 3 4]
  [4 0 3 0]]

 [[1 0 0 2]
  [4 3 2 4]
  [1 3 3 1]]]
(4, 3, 4)
3
48


In [33]:
print(f'Cada elemento possui {data.itemsize} bytes')
print(f'Toda a matriz possui {data.nbytes} bytes')

Cada elemento possui 4 bytes
Toda a matriz possui 192 bytes
