In [2]:
import numpy as np

In [3]:
data = np.array([2,4,6,8,10])

In [4]:
print(data)
print(type(data))
print(data.shape)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
(5,)


In [5]:
data = np.arange(15)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
data = np.random.rand(15)
print(data)

[0.04832158 0.76784528 0.09109409 0.94958692 0.15773438 0.46396401
 0.23585646 0.64026852 0.46006382 0.5635916  0.94360428 0.36425155
 0.7756589  0.14026503 0.06391798]


In [7]:
data = np.random.randint(10, size=10)
print(data)

[4 3 8 1 9 1 6 8 8 1]


In [8]:
data = np.random.random((2,2))
print(data)

[[0.96955901 0.94175523]
 [0.96254082 0.01052147]]


In [9]:
data = np.zeros((3,4))
print(data)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
data = np.ones((3,4))
print(data)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
data = np.empty((3,4))
print(data)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
data = np.arange(10) * -1
print(data)

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [13]:
tamanho = 10
data = np.random.permutation(tamanho)
print(data)

[2 8 1 6 5 4 0 3 7 9]


In [14]:
data = np.random.randint(5, size = 10)
print(data)
print(data.shape)

[2 0 3 1 3 0 4 0 4 1]
(10,)


In [15]:
data = np.random.randint(5, size = (3,4))
print(data)
print(data.shape)

[[2 1 3 4]
 [2 0 0 3]
 [1 3 0 2]]
(3, 4)


In [16]:
data = np.random.randint(5, size = (5,3,4))
print(data)
print(data.shape)

[[[2 3 2 4]
  [4 3 0 1]
  [4 3 2 2]]

 [[0 0 0 2]
  [1 4 1 3]
  [2 1 2 3]]

 [[4 2 3 2]
  [1 3 1 4]
  [2 1 0 4]]

 [[2 4 2 0]
  [4 3 1 2]
  [4 2 0 1]]

 [[2 3 2 1]
  [2 3 3 1]
  [1 1 4 3]]]
(5, 3, 4)


In [17]:
data = np.array([[1,2,3,4],[1,3,5,7]])
print(data)
print(data.shape)

[[1 2 3 4]
 [1 3 5 7]]
(2, 4)


In [18]:
data = np.array([(1,2,3,4),(1,3,5,7)])
print(data)
print(data.shape)
data_flat = data.flatten()
print(data_flat)
print(data_flat.shape)

[[1 2 3 4]
 [1 3 5 7]]
(2, 4)
[1 2 3 4 1 3 5 7]
(8,)


In [19]:
data = np.random.randint(5, size = (4,3,4))
print(data)
print(data.shape)
print(data.ndim)
print(data.size)

[[[3 2 0 1]
  [3 4 1 4]
  [3 4 1 2]]

 [[0 1 3 1]
  [3 3 2 1]
  [3 1 3 1]]

 [[1 0 3 2]
  [4 1 1 4]
  [2 0 3 3]]

 [[0 1 2 3]
  [3 3 4 1]
  [0 3 2 0]]]
(4, 3, 4)
3
48


In [20]:
print(f'Cada elemento possui {data.itemsize} bytes')
print(f'Toda a matriz possui {data.nbytes} bytes')

Cada elemento possui 4 bytes
Toda a matriz possui 192 bytes


In [21]:
data = np.arange(15)
print(data)
print(data.max())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14
